baseURL = "https://dormouseroared.github.io/hugo-scratch-1/"
languageCode = "en-us"
title = "green | hugo-scratch-1 | 0012"
publishDir = "docs"
enableGitInfo = true

[markup.goldmark.renderer]
unsafe= true  # allow HTML in Markdown files

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/:filename/"

[params]
    containerMaxWidth = "700px"
    dateFormat = "Jan 2, 2006"
    homeText = "Following the zwbetz Hugo tutorial:"
    tutorialName = "Make a Hugo blog from scratch"
    tutorialURL = "https://zwbetz.com/make-a-hugo-blog-from-scratch/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "Hugo Tips"
    pre = "paperclip"
    url = "/hugotips/"
    weight = 3
[[menu.main]]
    name = "testbundle"
    pre = "sliders"
    url = "/testbundle/"
    weight = 5
